pipeline {
    agent any
    
    tools {
        maven "maven3"
    }
    
    environment {
        SCANNER_HOME= tool 'sonar-scanner-tool' // tool name configured in jenkins
    }

    stages {
    /*
        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ibtisam-iq/Agri2Ops.git'
            }
        }
  */      
        stage('Compile') {
            steps {
                dir('03.Projects/00.LocalOps/0.1.01-jar_Boardgame') {
                sh "mvn compile"
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('03.Projects/00.LocalOps/0.1.01-jar_Boardgame') {
                    sh "mvn test"
                }    
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                dir('03.Projects/00.LocalOps/0.1.01-jar_Boardgame') {
                    withSonarQubeEnv('sonar-server') {                 // server name configured in jenkins
                        sh '''
                        $SCANNER_HOME/bin/sonar-scanner \              
                        '''
                        /*
                            -Dsonar.projectName=Boardgame \
                            -Dsonar.projectKey=boardgame \
                            -Dsonar.java.binaries=target \
                            -Dsonar.branch.name=ibtisam
                        */
                    }
                }
            }
        }
        
        stage('Quality Gate Check') {
            steps {
                dir('03.Projects/00.LocalOps/0.1.01-jar_Boardgame') {
                    timeout(time: 1, unit: 'HOURS') {
                        waitForQualityGate abortPipeline: false
                    }
                }
            }
        }
        
        stage('Package') {
            steps {
                dir('03.Projects/00.LocalOps/0.1.01-jar_Boardgame') {
                    sh "mvn package"
                }
            }
        }
        
        stage('Love') {
            steps {
                echo 'Love you, Sweetheart'
            }
        }
    }
}
