services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
  # ports:
  #   - "3306:3306"          # Never Expose MySQL, it is a security risk meri jaan 😘        
    volumes:
      - db_data:/var/lib/mysql     
    # - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - app-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "--user=$MYSQL_USER", "--password=$MYSQL_PASSWORD"]  
      interval: 30s
      timeout: 10s
      retries: 3

  server:
    build: ./server
    container_name: server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"                  # Expose app on port 5000
    depends_on:
      - db:
        condition: service_healthy   # Wait for MySQL to be healthy before starting the app
    networks:
      - app-network

  client:
    build: ./client
    container_name: client
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - server

networks:
  app-network:

volumes:
  db_data: