services:
  web:
    build: .  # Builds the Spring Boot application from the Dockerfile
    image: multi-stage-build-bankapp  # Names the built image
    container_name: bank-web  # Names the running container for easy identification
    restart: unless-stopped  # Ensures the app restarts automatically unless manually stopped
    ports:
      - "8000:8000"  # Maps port 8080 on the container to port 8080 on the host machine

    # Loads environment variables from a .env file (instead of hardcoding in this file)
    env_file:
      - .env
    #environment:
      #- SPRING_DATASOURCE_URL=jdbc:$SPRING_DATASOURCE_URL
      #- SPRING_DATASOURCE_USERNAME=$MYSQL_USER
      #- SPRING_JPA_HIBERNATE_DDL_AUTO=$SPRING_JPA_HIBERNATE_DDL_AUTO  # Use env variables for other spring properties
      #- SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=$SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
      #- SPRING_JPA_SHOW_SQL=$SPRING_JPA_SHOW_SQL

    depends_on:
      db:
        condition: service_healthy  # Ensures MySQL container is healthy before starting the app
        # ⚠️ NOTE: Even though MySQL is marked as healthy, it might still be initializing tables.
        #          We fix this inside application.properties.

    networks:
      - app-network  # Attaches the web service to the custom-defined network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]  
      # ✅ Checks if the Spring Boot application is running by pinging its health endpoint
      interval: 30s  # Runs the health check every 30 seconds
      timeout: 10s   # Fails if there is no response within 10 seconds
      retries: 3     # Retries 3 times before marking the service as unhealthy

    #working_dir: /usr/src/app  # ✅ Sets the working directory inside the container for locating wait-for-it.sh  

  # entrypoint: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "app.jar"]  
      # ✅ Ensures MySQL is fully ready before launching the application  

  db:
    image: mysql:8  # Uses the latest official MySQL image
    container_name: mysql-db  # Assigns a name to the database container
    restart: unless-stopped  # Ensures MySQL restarts unless manually stopped

    # Loads environment variables from a .env file
    env_file: 
      - .env
    #environment:
        #MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD  # Sets the MySQL root password from the .env file
        #MYSQL_DATABASE: $MYSQL_DATABASE  # Sets the MySQL database name from the .env file
        #MYSQL_USER: $MYSQL_USER  # Sets the MySQL user from the .env file
        #MYSQL_PASSWORD: $MYSQL_PASSWORD  # Sets the MySQL user password from the .env file
        
    ports:
      - "3306:3306"  # Never Expose MySQL, it is a security risk meri jaan 😘

    volumes:
      - mysql_data_8:/var/lib/mysql  # ✅ Ensures MySQL data persists across container restarts

    networks:
      - app-network  # Attaches MySQL to the same network as the app

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]  
      # ✅ Checks if MySQL is running and accepting connections
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge  # Uses a bridge network to allow communication between services

volumes:
  mysql_data_8:  # Named volume for persisting MySQL database files
