services:
  java-app:
    build: 
      context: .
      dockerfile: Dockerfile.multi
    image: multi-stage-with-maven-prebuilt

    container_name: java-container
    ports:
      - "3395:3395"
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m # Explicit Java memory limits improve stability.
    #command: ["java", "-jar", "/usr/src/app/app.jar"] # must be the correct path in the container

