services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.multi
    image: multi-build-blogapp
    container_name: blogapp
  # command: java -jar /usr/src/app/app.jar # target/*.jar ; wrong path in the container
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3  

# NETWORK ID     NAME                              DRIVER    SCOPE
# 496afd05355f   3tierjavaboardgamedb-h2_default   bridge    local
# This network is created automatically by Docker Compose when you bring up the services defined in the docker-compose.yml file.

