FROM maven:3.9.9-eclipse-temurin-17-alpine

WORKDIR /usr/src/app

COPY . .

RUN mvn package -DskipTests

EXPOSE 8080

CMD ["sh", "-c", "java -jar $(ls /usr/src/app/target/*.jar | head -n 1)"]





# ----------------------------------------------------------------

# REPOSITORY                                 TAG                  IMAGE ID       CREATED              SIZE
# single-build-blogapp-with-maven-prebuilt   latest               cac44b3d6b98   About a minute ago   498MB
    