version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ibtisam
      POSTGRES_PASSWORD: ibtisam
      POSTGRES_DB: loveyou_ibtisam
      # please check config and change the SQLALCHEMY_DATABASE_URI to your own database URI

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://ibtisam:ibtisam@db/loveyou_ibtisam
      
volumes:
  postgres_data:
