services:
  db:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    # ports:
    #  - "27017:27017"  # Expose MongoDB for local development (remove in production)
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  webapp:
    build: .
    container_name: dotnet-mongo-crud
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDB__ConnectionString: "mongodb://${MONGO_USER}:${MONGO_PASS}@db:27017"
      MongoDB__DatabaseName: ${MONGO_DB}
    ports:
      - "5035:5035"  # Matches .NET default Kestrel port
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro  # Read-only for security

volumes:
  mongo-data:
